import "@uploadthing/react/styles.css";
import { type Session } from "next-auth";
import { SessionProvider } from "next-auth/react";
import { type AppType } from "next/app";
import Head from "next/head";
import Navbar from "~/components/navbar/navbar";
import "~/styles/globals.css";
import { api } from "~/utils/api";
import { Toaster } from "react-hot-toast";

const MyApp: AppType<{ session: Session | null }> = ({
  Component,
  pageProps: { session, ...pageProps },
}) => {
  return (
    <SessionProvider session={session}>
      <Head>
        <title>Blogging engine</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className="flex h-full flex-1 flex-col items-start justify-start gap-16 px-10 py-16 lg:px-pageGutter">
        <Component {...pageProps} />
      </main>
      <Toaster position="bottom-right" />
    </SessionProvider>
  );
};

export default api.withTRPC(MyApp);
