import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { Navbar } from "~/components/navbar";
import { Posts } from "~/components/posts";
import { api } from "~/utils/api";

export default function About() {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className="flex min-h-screen flex-1 flex-col items-start justify-center gap-16 py-16 pl-pageGutter">
        about uts
      </main>
    </>
  );
}
